
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `metaPackage`=list(
        `type`="article", 
        `author`="Sara Balduzzi and Gerta R\u00FCcker and Guido Schwarzer", 
        `year`=2019, 
        `title`="How to perform a meta-analysis with R: a practical tutorial", 
        `publisher`="Evidence-Based Mental Health", 
        `pages`="153-160", 
        `url`="https://http://10.1136/ebmental-2019-300117"), 
    `metaforPackage`=list(
        `type`="article", 
        `author`="Wolfgang Viechtbauer", 
        `year`=2010, 
        `title`="Conducting meta-analyses in R with the metafor package", 
        `publisher`="Journal of Statistical Software", 
        `volume`=36, 
        `pages`="1-48", 
        `url`="https://http://doi.org/10.18637/jss.v036.i03"), 
    `eggerTest`=list(
        `type`="article", 
        `author`="Matthias Egger, George Davey Smith, Martin Schneider, Christoph Minder", 
        `year`=1997, 
        `title`="Bias in meta-analysis detected by a simple, graphical test", 
        `publisher`="BMJ (British Medical Journal)", 
        `volume`=315, 
        `pages`="629\u2013634", 
        `doi`="10.1136/bmj.315.7109.629"), 
    `lfkTest`=list(
        `type`="article", 
        `author`="Luis Furuya-Kanamori, Jan J. Barendregt, Suhail A.R. Doi", 
        `year`=2018, 
        `title`="A new improved graphical and quantitative method for detecting bias in meta-analysis", 
        `publisher`="International Journal of Evidence-Based Healthcare", 
        `volume`=16, 
        `pages`="1\u20139", 
        `doi`="10.1097/XEB.0000000000000141"))
