
# This file is automatically generated, you probably don't want to edit this

metaContOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "metaContOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            studyLabel = NULL,
            meanE = NULL,
            sdE = NULL,
            nE = NULL,
            meanC = NULL,
            sdC = NULL,
            nC = NULL,
            sm = "md",
            methodSmd = "Hedges",
            random = TRUE,
            common = TRUE,
            methodTau = "REML",
            methodRandomCi = "classic",
            adhocHaknCi = "none",
            prediction = FALSE,
            confidenceLevel = 0.95,
            showSummary = TRUE,
            forestPlot = TRUE,
            forestLayout = "meta",
            sortBy = "none",
            labelLeft = "",
            labelRight = "",
            labelE = "Experimental",
            labelC = "Control", ...) {

            super$initialize(
                package="MetaPort",
                name="metaCont",
                requiresData=TRUE,
                ...)

            private$..studyLabel <- jmvcore::OptionVariable$new(
                "studyLabel",
                studyLabel,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor",
                    "id"))
            private$..meanE <- jmvcore::OptionVariable$new(
                "meanE",
                meanE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sdE <- jmvcore::OptionVariable$new(
                "sdE",
                sdE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..nE <- jmvcore::OptionVariable$new(
                "nE",
                nE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..meanC <- jmvcore::OptionVariable$new(
                "meanC",
                meanC,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sdC <- jmvcore::OptionVariable$new(
                "sdC",
                sdC,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..nC <- jmvcore::OptionVariable$new(
                "nC",
                nC,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sm <- jmvcore::OptionList$new(
                "sm",
                sm,
                options=list(
                    "md",
                    "smd",
                    "rom"),
                default="md")
            private$..methodSmd <- jmvcore::OptionList$new(
                "methodSmd",
                methodSmd,
                options=list(
                    "Hedges",
                    "Cohen",
                    "Glass"),
                default="Hedges")
            private$..random <- jmvcore::OptionBool$new(
                "random",
                random,
                default=TRUE)
            private$..common <- jmvcore::OptionBool$new(
                "common",
                common,
                default=TRUE)
            private$..methodTau <- jmvcore::OptionList$new(
                "methodTau",
                methodTau,
                options=list(
                    "REML",
                    "DL",
                    "PM",
                    "ML",
                    "HS",
                    "SJ",
                    "HE",
                    "EB"),
                default="REML")
            private$..methodRandomCi <- jmvcore::OptionList$new(
                "methodRandomCi",
                methodRandomCi,
                options=list(
                    "classic",
                    "HK"),
                default="classic")
            private$..adhocHaknCi <- jmvcore::OptionList$new(
                "adhocHaknCi",
                adhocHaknCi,
                options=list(
                    "none",
                    "se",
                    "IQR",
                    "ci"),
                default="none")
            private$..prediction <- jmvcore::OptionBool$new(
                "prediction",
                prediction,
                default=FALSE)
            private$..confidenceLevel <- jmvcore::OptionNumber$new(
                "confidenceLevel",
                confidenceLevel,
                default=0.95)
            private$..showSummary <- jmvcore::OptionBool$new(
                "showSummary",
                showSummary,
                default=TRUE)
            private$..forestPlot <- jmvcore::OptionBool$new(
                "forestPlot",
                forestPlot,
                default=TRUE)
            private$..forestLayout <- jmvcore::OptionList$new(
                "forestLayout",
                forestLayout,
                options=list(
                    "meta",
                    "RevMan5",
                    "JAMA",
                    "BMJ"),
                default="meta")
            private$..sortBy <- jmvcore::OptionList$new(
                "sortBy",
                sortBy,
                options=list(
                    "none",
                    "effectAsc",
                    "effectDesc",
                    "weightAsc",
                    "weightDesc"),
                default="none")
            private$..labelLeft <- jmvcore::OptionString$new(
                "labelLeft",
                labelLeft,
                default="")
            private$..labelRight <- jmvcore::OptionString$new(
                "labelRight",
                labelRight,
                default="")
            private$..labelE <- jmvcore::OptionString$new(
                "labelE",
                labelE,
                default="Experimental")
            private$..labelC <- jmvcore::OptionString$new(
                "labelC",
                labelC,
                default="Control")

            self$.addOption(private$..studyLabel)
            self$.addOption(private$..meanE)
            self$.addOption(private$..sdE)
            self$.addOption(private$..nE)
            self$.addOption(private$..meanC)
            self$.addOption(private$..sdC)
            self$.addOption(private$..nC)
            self$.addOption(private$..sm)
            self$.addOption(private$..methodSmd)
            self$.addOption(private$..random)
            self$.addOption(private$..common)
            self$.addOption(private$..methodTau)
            self$.addOption(private$..methodRandomCi)
            self$.addOption(private$..adhocHaknCi)
            self$.addOption(private$..prediction)
            self$.addOption(private$..confidenceLevel)
            self$.addOption(private$..showSummary)
            self$.addOption(private$..forestPlot)
            self$.addOption(private$..forestLayout)
            self$.addOption(private$..sortBy)
            self$.addOption(private$..labelLeft)
            self$.addOption(private$..labelRight)
            self$.addOption(private$..labelE)
            self$.addOption(private$..labelC)
        }),
    active = list(
        studyLabel = function() private$..studyLabel$value,
        meanE = function() private$..meanE$value,
        sdE = function() private$..sdE$value,
        nE = function() private$..nE$value,
        meanC = function() private$..meanC$value,
        sdC = function() private$..sdC$value,
        nC = function() private$..nC$value,
        sm = function() private$..sm$value,
        methodSmd = function() private$..methodSmd$value,
        random = function() private$..random$value,
        common = function() private$..common$value,
        methodTau = function() private$..methodTau$value,
        methodRandomCi = function() private$..methodRandomCi$value,
        adhocHaknCi = function() private$..adhocHaknCi$value,
        prediction = function() private$..prediction$value,
        confidenceLevel = function() private$..confidenceLevel$value,
        showSummary = function() private$..showSummary$value,
        forestPlot = function() private$..forestPlot$value,
        forestLayout = function() private$..forestLayout$value,
        sortBy = function() private$..sortBy$value,
        labelLeft = function() private$..labelLeft$value,
        labelRight = function() private$..labelRight$value,
        labelE = function() private$..labelE$value,
        labelC = function() private$..labelC$value),
    private = list(
        ..studyLabel = NA,
        ..meanE = NA,
        ..sdE = NA,
        ..nE = NA,
        ..meanC = NA,
        ..sdC = NA,
        ..nC = NA,
        ..sm = NA,
        ..methodSmd = NA,
        ..random = NA,
        ..common = NA,
        ..methodTau = NA,
        ..methodRandomCi = NA,
        ..adhocHaknCi = NA,
        ..prediction = NA,
        ..confidenceLevel = NA,
        ..showSummary = NA,
        ..forestPlot = NA,
        ..forestLayout = NA,
        ..sortBy = NA,
        ..labelLeft = NA,
        ..labelRight = NA,
        ..labelE = NA,
        ..labelC = NA)
)

metaContResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "metaContResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Continuous Meta-Analysis")
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                title="Overall Meta-Analysis Results",
                visible="(showSummary)",
                clearWith=list(
                    "meanE",
                    "sdE",
                    "nE",
                    "meanC",
                    "sdC",
                    "nC",
                    "studyLabel",
                    "sm",
                    "methodTau",
                    "methodSmd",
                    "methodRandomCi",
                    "adhocHaknCi",
                    "random",
                    "common",
                    "prediction",
                    "confidenceLevel"),
                refs=list(
                    "metaPackage")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Forest Plot",
                renderFun=".forestPlot",
                visible="(forestPlot)",
                requiresData=TRUE,
                clearWith=list(
                    "meanE",
                    "sdE",
                    "nE",
                    "meanC",
                    "sdC",
                    "nC",
                    "studyLabel",
                    "sm",
                    "methodTau",
                    "methodSmd",
                    "methodRandomCi",
                    "adhocHaknCi",
                    "random",
                    "common",
                    "prediction",
                    "confidenceLevel",
                    "forestLayout",
                    "sortBy",
                    "labelLeft",
                    "labelRight",
                    "labelE",
                    "labelC"),
                refs=list(
                    "metaPackage")))}))

metaContBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "metaContBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "MetaPort",
                name = "metaCont",
                version = c(1,0,0),
                options = options,
                results = metaContResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Continuous Meta-Analysis
#'
#' 
#' @param data .
#' @param studyLabel .
#' @param meanE .
#' @param sdE .
#' @param nE .
#' @param meanC .
#' @param sdC .
#' @param nC .
#' @param sm .
#' @param methodSmd .
#' @param random .
#' @param common .
#' @param methodTau .
#' @param methodRandomCi .
#' @param adhocHaknCi .
#' @param prediction .
#' @param confidenceLevel .
#' @param showSummary .
#' @param forestPlot .
#' @param forestLayout .
#' @param sortBy .
#' @param labelLeft .
#' @param labelRight .
#' @param labelE .
#' @param labelC .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
metaCont <- function(
    data,
    studyLabel,
    meanE,
    sdE,
    nE,
    meanC,
    sdC,
    nC,
    sm = "md",
    methodSmd = "Hedges",
    random = TRUE,
    common = TRUE,
    methodTau = "REML",
    methodRandomCi = "classic",
    adhocHaknCi = "none",
    prediction = FALSE,
    confidenceLevel = 0.95,
    showSummary = TRUE,
    forestPlot = TRUE,
    forestLayout = "meta",
    sortBy = "none",
    labelLeft = "",
    labelRight = "",
    labelE = "Experimental",
    labelC = "Control") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("metaCont requires jmvcore to be installed (restart may be required)")

    if ( ! missing(studyLabel)) studyLabel <- jmvcore::resolveQuo(jmvcore::enquo(studyLabel))
    if ( ! missing(meanE)) meanE <- jmvcore::resolveQuo(jmvcore::enquo(meanE))
    if ( ! missing(sdE)) sdE <- jmvcore::resolveQuo(jmvcore::enquo(sdE))
    if ( ! missing(nE)) nE <- jmvcore::resolveQuo(jmvcore::enquo(nE))
    if ( ! missing(meanC)) meanC <- jmvcore::resolveQuo(jmvcore::enquo(meanC))
    if ( ! missing(sdC)) sdC <- jmvcore::resolveQuo(jmvcore::enquo(sdC))
    if ( ! missing(nC)) nC <- jmvcore::resolveQuo(jmvcore::enquo(nC))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(studyLabel), studyLabel, NULL),
            `if`( ! missing(meanE), meanE, NULL),
            `if`( ! missing(sdE), sdE, NULL),
            `if`( ! missing(nE), nE, NULL),
            `if`( ! missing(meanC), meanC, NULL),
            `if`( ! missing(sdC), sdC, NULL),
            `if`( ! missing(nC), nC, NULL))


    options <- metaContOptions$new(
        studyLabel = studyLabel,
        meanE = meanE,
        sdE = sdE,
        nE = nE,
        meanC = meanC,
        sdC = sdC,
        nC = nC,
        sm = sm,
        methodSmd = methodSmd,
        random = random,
        common = common,
        methodTau = methodTau,
        methodRandomCi = methodRandomCi,
        adhocHaknCi = adhocHaknCi,
        prediction = prediction,
        confidenceLevel = confidenceLevel,
        showSummary = showSummary,
        forestPlot = forestPlot,
        forestLayout = forestLayout,
        sortBy = sortBy,
        labelLeft = labelLeft,
        labelRight = labelRight,
        labelE = labelE,
        labelC = labelC)

    analysis <- metaContClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

