
# This file is automatically generated, you probably don't want to edit this

metaContOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "metaContOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            studyLabel = NULL,
            meanE = NULL,
            sdE = NULL,
            nE = NULL,
            meanC = NULL,
            sdC = NULL,
            nC = NULL,
            sm = "md",
            methodSmd = "Hedges",
            model = "both",
            methodTau = "REML",
            methodRandomCi = "classic",
            prediction = FALSE,
            confidenceLevel = 95,
            showSummary = TRUE,
            forestPlot = TRUE,
            forestMode = "basic",
            forestLayout = "meta",
            sortBy = "none",
            labelE = "Experimental",
            labelC = "Control",
            labelLeft = "",
            labelRight = "",
            forestWidthAdjust = 0,
            forestWidthUnit = "mm",
            forestHeightAdjust = 0,
            forestHeightUnit = "mm",
            xlimMode = "auto",
            xlimLower = -20,
            xlimUpper = 20,
            addrowsMode = "auto",
            addrowsBelowOverall = 0,
            colgap = 2,
            colgapUnit = "mm",
            colgapForest = 2,
            colgapForestUnit = "mm",
            subgroupVariable = NULL,
            tauCommon = FALSE,
            predictionSubgroup = FALSE,
            showSubgroupSummary = TRUE,
            subgroupForestPlot = TRUE,
            subgroupForestMode = "basic",
            printSubgroupName = TRUE,
            subgroupForestLayout = "meta",
            subgroupSortBy = "none",
            subgroupLabelE = "Experimental",
            subgroupLabelC = "Control",
            subgroupLabelLeft = "",
            subgroupLabelRight = "",
            subgroupForestWidthAdjust = 0,
            subgroupForestWidthUnit = "mm",
            subgroupForestHeightAdjust = 0,
            subgroupForestHeightUnit = "mm",
            subgroupXlimMode = "auto",
            subgroupXlimLower = -20,
            subgroupXlimUpper = 20,
            subgroupAddrowsMode = "auto",
            subgroupAddrowsBelowOverall = 0,
            subgroupColgap = 2,
            subgroupColgapUnit = "mm",
            subgroupColgapForest = 2,
            subgroupColgapForestUnit = "mm", ...) {

            super$initialize(
                package="MetaPort",
                name="metaCont",
                requiresData=TRUE,
                ...)

            private$..studyLabel <- jmvcore::OptionVariable$new(
                "studyLabel",
                studyLabel,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor",
                    "id"))
            private$..meanE <- jmvcore::OptionVariable$new(
                "meanE",
                meanE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sdE <- jmvcore::OptionVariable$new(
                "sdE",
                sdE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..nE <- jmvcore::OptionVariable$new(
                "nE",
                nE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..meanC <- jmvcore::OptionVariable$new(
                "meanC",
                meanC,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sdC <- jmvcore::OptionVariable$new(
                "sdC",
                sdC,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..nC <- jmvcore::OptionVariable$new(
                "nC",
                nC,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sm <- jmvcore::OptionList$new(
                "sm",
                sm,
                options=list(
                    "md",
                    "smd",
                    "rom"),
                default="md")
            private$..methodSmd <- jmvcore::OptionList$new(
                "methodSmd",
                methodSmd,
                options=list(
                    "Hedges",
                    "Cohen",
                    "Glass"),
                default="Hedges")
            private$..model <- jmvcore::OptionList$new(
                "model",
                model,
                options=list(
                    "both",
                    "random",
                    "common"),
                default="both")
            private$..methodTau <- jmvcore::OptionList$new(
                "methodTau",
                methodTau,
                options=list(
                    "REML",
                    "PM",
                    "DL",
                    "ML",
                    "HS",
                    "SJ",
                    "HE",
                    "EB"),
                default="REML")
            private$..methodRandomCi <- jmvcore::OptionList$new(
                "methodRandomCi",
                methodRandomCi,
                options=list(
                    "classic",
                    "HK"),
                default="classic")
            private$..prediction <- jmvcore::OptionBool$new(
                "prediction",
                prediction,
                default=FALSE)
            private$..confidenceLevel <- jmvcore::OptionNumber$new(
                "confidenceLevel",
                confidenceLevel,
                min=50,
                max=99.9,
                default=95)
            private$..showSummary <- jmvcore::OptionBool$new(
                "showSummary",
                showSummary,
                default=TRUE)
            private$..forestPlot <- jmvcore::OptionBool$new(
                "forestPlot",
                forestPlot,
                default=TRUE)
            private$..forestMode <- jmvcore::OptionList$new(
                "forestMode",
                forestMode,
                options=list(
                    "basic",
                    "advanced"),
                default="basic")
            private$..forestLayout <- jmvcore::OptionList$new(
                "forestLayout",
                forestLayout,
                options=list(
                    "meta",
                    "RevMan5",
                    "JAMA",
                    "BMJ"),
                default="meta")
            private$..sortBy <- jmvcore::OptionList$new(
                "sortBy",
                sortBy,
                options=list(
                    "none",
                    "effectAsc",
                    "effectDesc",
                    "weightAsc",
                    "weightDesc"),
                default="none")
            private$..labelE <- jmvcore::OptionString$new(
                "labelE",
                labelE,
                default="Experimental")
            private$..labelC <- jmvcore::OptionString$new(
                "labelC",
                labelC,
                default="Control")
            private$..labelLeft <- jmvcore::OptionString$new(
                "labelLeft",
                labelLeft,
                default="")
            private$..labelRight <- jmvcore::OptionString$new(
                "labelRight",
                labelRight,
                default="")
            private$..forestWidthAdjust <- jmvcore::OptionNumber$new(
                "forestWidthAdjust",
                forestWidthAdjust,
                default=0)
            private$..forestWidthUnit <- jmvcore::OptionList$new(
                "forestWidthUnit",
                forestWidthUnit,
                options=list(
                    "mm",
                    "cm",
                    "inch"),
                default="mm")
            private$..forestHeightAdjust <- jmvcore::OptionNumber$new(
                "forestHeightAdjust",
                forestHeightAdjust,
                default=0)
            private$..forestHeightUnit <- jmvcore::OptionList$new(
                "forestHeightUnit",
                forestHeightUnit,
                options=list(
                    "mm",
                    "cm",
                    "inch"),
                default="mm")
            private$..xlimMode <- jmvcore::OptionList$new(
                "xlimMode",
                xlimMode,
                options=list(
                    "auto",
                    "custom"),
                default="auto")
            private$..xlimLower <- jmvcore::OptionNumber$new(
                "xlimLower",
                xlimLower,
                default=-20)
            private$..xlimUpper <- jmvcore::OptionNumber$new(
                "xlimUpper",
                xlimUpper,
                default=20)
            private$..addrowsMode <- jmvcore::OptionList$new(
                "addrowsMode",
                addrowsMode,
                options=list(
                    "auto",
                    "custom"),
                default="auto")
            private$..addrowsBelowOverall <- jmvcore::OptionInteger$new(
                "addrowsBelowOverall",
                addrowsBelowOverall,
                min=0,
                default=0)
            private$..colgap <- jmvcore::OptionNumber$new(
                "colgap",
                colgap,
                min=0,
                default=2)
            private$..colgapUnit <- jmvcore::OptionList$new(
                "colgapUnit",
                colgapUnit,
                options=list(
                    "mm",
                    "cm",
                    "inch"),
                default="mm")
            private$..colgapForest <- jmvcore::OptionNumber$new(
                "colgapForest",
                colgapForest,
                min=0,
                default=2)
            private$..colgapForestUnit <- jmvcore::OptionList$new(
                "colgapForestUnit",
                colgapForestUnit,
                options=list(
                    "mm",
                    "cm",
                    "inch"),
                default="mm")
            private$..subgroupVariable <- jmvcore::OptionVariable$new(
                "subgroupVariable",
                subgroupVariable,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor",
                    "id"))
            private$..tauCommon <- jmvcore::OptionBool$new(
                "tauCommon",
                tauCommon,
                default=FALSE)
            private$..predictionSubgroup <- jmvcore::OptionBool$new(
                "predictionSubgroup",
                predictionSubgroup,
                default=FALSE)
            private$..showSubgroupSummary <- jmvcore::OptionBool$new(
                "showSubgroupSummary",
                showSubgroupSummary,
                default=TRUE)
            private$..subgroupForestPlot <- jmvcore::OptionBool$new(
                "subgroupForestPlot",
                subgroupForestPlot,
                default=TRUE)
            private$..subgroupForestMode <- jmvcore::OptionList$new(
                "subgroupForestMode",
                subgroupForestMode,
                options=list(
                    "basic",
                    "advanced"),
                default="basic")
            private$..printSubgroupName <- jmvcore::OptionBool$new(
                "printSubgroupName",
                printSubgroupName,
                default=TRUE)
            private$..subgroupForestLayout <- jmvcore::OptionList$new(
                "subgroupForestLayout",
                subgroupForestLayout,
                options=list(
                    "meta",
                    "RevMan5",
                    "JAMA",
                    "BMJ",
                    "subgroup"),
                default="meta")
            private$..subgroupSortBy <- jmvcore::OptionList$new(
                "subgroupSortBy",
                subgroupSortBy,
                options=list(
                    "none",
                    "effectAsc",
                    "effectDesc",
                    "weightAsc",
                    "weightDesc"),
                default="none")
            private$..subgroupLabelE <- jmvcore::OptionString$new(
                "subgroupLabelE",
                subgroupLabelE,
                default="Experimental")
            private$..subgroupLabelC <- jmvcore::OptionString$new(
                "subgroupLabelC",
                subgroupLabelC,
                default="Control")
            private$..subgroupLabelLeft <- jmvcore::OptionString$new(
                "subgroupLabelLeft",
                subgroupLabelLeft,
                default="")
            private$..subgroupLabelRight <- jmvcore::OptionString$new(
                "subgroupLabelRight",
                subgroupLabelRight,
                default="")
            private$..subgroupForestWidthAdjust <- jmvcore::OptionNumber$new(
                "subgroupForestWidthAdjust",
                subgroupForestWidthAdjust,
                default=0)
            private$..subgroupForestWidthUnit <- jmvcore::OptionList$new(
                "subgroupForestWidthUnit",
                subgroupForestWidthUnit,
                options=list(
                    "mm",
                    "cm",
                    "inch"),
                default="mm")
            private$..subgroupForestHeightAdjust <- jmvcore::OptionNumber$new(
                "subgroupForestHeightAdjust",
                subgroupForestHeightAdjust,
                default=0)
            private$..subgroupForestHeightUnit <- jmvcore::OptionList$new(
                "subgroupForestHeightUnit",
                subgroupForestHeightUnit,
                options=list(
                    "mm",
                    "cm",
                    "inch"),
                default="mm")
            private$..subgroupXlimMode <- jmvcore::OptionList$new(
                "subgroupXlimMode",
                subgroupXlimMode,
                options=list(
                    "auto",
                    "custom"),
                default="auto")
            private$..subgroupXlimLower <- jmvcore::OptionNumber$new(
                "subgroupXlimLower",
                subgroupXlimLower,
                default=-20)
            private$..subgroupXlimUpper <- jmvcore::OptionNumber$new(
                "subgroupXlimUpper",
                subgroupXlimUpper,
                default=20)
            private$..subgroupAddrowsMode <- jmvcore::OptionList$new(
                "subgroupAddrowsMode",
                subgroupAddrowsMode,
                options=list(
                    "auto",
                    "custom"),
                default="auto")
            private$..subgroupAddrowsBelowOverall <- jmvcore::OptionInteger$new(
                "subgroupAddrowsBelowOverall",
                subgroupAddrowsBelowOverall,
                min=0,
                default=0)
            private$..subgroupColgap <- jmvcore::OptionNumber$new(
                "subgroupColgap",
                subgroupColgap,
                min=0,
                default=2)
            private$..subgroupColgapUnit <- jmvcore::OptionList$new(
                "subgroupColgapUnit",
                subgroupColgapUnit,
                options=list(
                    "mm",
                    "cm",
                    "inch"),
                default="mm")
            private$..subgroupColgapForest <- jmvcore::OptionNumber$new(
                "subgroupColgapForest",
                subgroupColgapForest,
                min=0,
                default=2)
            private$..subgroupColgapForestUnit <- jmvcore::OptionList$new(
                "subgroupColgapForestUnit",
                subgroupColgapForestUnit,
                options=list(
                    "mm",
                    "cm",
                    "inch"),
                default="mm")

            self$.addOption(private$..studyLabel)
            self$.addOption(private$..meanE)
            self$.addOption(private$..sdE)
            self$.addOption(private$..nE)
            self$.addOption(private$..meanC)
            self$.addOption(private$..sdC)
            self$.addOption(private$..nC)
            self$.addOption(private$..sm)
            self$.addOption(private$..methodSmd)
            self$.addOption(private$..model)
            self$.addOption(private$..methodTau)
            self$.addOption(private$..methodRandomCi)
            self$.addOption(private$..prediction)
            self$.addOption(private$..confidenceLevel)
            self$.addOption(private$..showSummary)
            self$.addOption(private$..forestPlot)
            self$.addOption(private$..forestMode)
            self$.addOption(private$..forestLayout)
            self$.addOption(private$..sortBy)
            self$.addOption(private$..labelE)
            self$.addOption(private$..labelC)
            self$.addOption(private$..labelLeft)
            self$.addOption(private$..labelRight)
            self$.addOption(private$..forestWidthAdjust)
            self$.addOption(private$..forestWidthUnit)
            self$.addOption(private$..forestHeightAdjust)
            self$.addOption(private$..forestHeightUnit)
            self$.addOption(private$..xlimMode)
            self$.addOption(private$..xlimLower)
            self$.addOption(private$..xlimUpper)
            self$.addOption(private$..addrowsMode)
            self$.addOption(private$..addrowsBelowOverall)
            self$.addOption(private$..colgap)
            self$.addOption(private$..colgapUnit)
            self$.addOption(private$..colgapForest)
            self$.addOption(private$..colgapForestUnit)
            self$.addOption(private$..subgroupVariable)
            self$.addOption(private$..tauCommon)
            self$.addOption(private$..predictionSubgroup)
            self$.addOption(private$..showSubgroupSummary)
            self$.addOption(private$..subgroupForestPlot)
            self$.addOption(private$..subgroupForestMode)
            self$.addOption(private$..printSubgroupName)
            self$.addOption(private$..subgroupForestLayout)
            self$.addOption(private$..subgroupSortBy)
            self$.addOption(private$..subgroupLabelE)
            self$.addOption(private$..subgroupLabelC)
            self$.addOption(private$..subgroupLabelLeft)
            self$.addOption(private$..subgroupLabelRight)
            self$.addOption(private$..subgroupForestWidthAdjust)
            self$.addOption(private$..subgroupForestWidthUnit)
            self$.addOption(private$..subgroupForestHeightAdjust)
            self$.addOption(private$..subgroupForestHeightUnit)
            self$.addOption(private$..subgroupXlimMode)
            self$.addOption(private$..subgroupXlimLower)
            self$.addOption(private$..subgroupXlimUpper)
            self$.addOption(private$..subgroupAddrowsMode)
            self$.addOption(private$..subgroupAddrowsBelowOverall)
            self$.addOption(private$..subgroupColgap)
            self$.addOption(private$..subgroupColgapUnit)
            self$.addOption(private$..subgroupColgapForest)
            self$.addOption(private$..subgroupColgapForestUnit)
        }),
    active = list(
        studyLabel = function() private$..studyLabel$value,
        meanE = function() private$..meanE$value,
        sdE = function() private$..sdE$value,
        nE = function() private$..nE$value,
        meanC = function() private$..meanC$value,
        sdC = function() private$..sdC$value,
        nC = function() private$..nC$value,
        sm = function() private$..sm$value,
        methodSmd = function() private$..methodSmd$value,
        model = function() private$..model$value,
        methodTau = function() private$..methodTau$value,
        methodRandomCi = function() private$..methodRandomCi$value,
        prediction = function() private$..prediction$value,
        confidenceLevel = function() private$..confidenceLevel$value,
        showSummary = function() private$..showSummary$value,
        forestPlot = function() private$..forestPlot$value,
        forestMode = function() private$..forestMode$value,
        forestLayout = function() private$..forestLayout$value,
        sortBy = function() private$..sortBy$value,
        labelE = function() private$..labelE$value,
        labelC = function() private$..labelC$value,
        labelLeft = function() private$..labelLeft$value,
        labelRight = function() private$..labelRight$value,
        forestWidthAdjust = function() private$..forestWidthAdjust$value,
        forestWidthUnit = function() private$..forestWidthUnit$value,
        forestHeightAdjust = function() private$..forestHeightAdjust$value,
        forestHeightUnit = function() private$..forestHeightUnit$value,
        xlimMode = function() private$..xlimMode$value,
        xlimLower = function() private$..xlimLower$value,
        xlimUpper = function() private$..xlimUpper$value,
        addrowsMode = function() private$..addrowsMode$value,
        addrowsBelowOverall = function() private$..addrowsBelowOverall$value,
        colgap = function() private$..colgap$value,
        colgapUnit = function() private$..colgapUnit$value,
        colgapForest = function() private$..colgapForest$value,
        colgapForestUnit = function() private$..colgapForestUnit$value,
        subgroupVariable = function() private$..subgroupVariable$value,
        tauCommon = function() private$..tauCommon$value,
        predictionSubgroup = function() private$..predictionSubgroup$value,
        showSubgroupSummary = function() private$..showSubgroupSummary$value,
        subgroupForestPlot = function() private$..subgroupForestPlot$value,
        subgroupForestMode = function() private$..subgroupForestMode$value,
        printSubgroupName = function() private$..printSubgroupName$value,
        subgroupForestLayout = function() private$..subgroupForestLayout$value,
        subgroupSortBy = function() private$..subgroupSortBy$value,
        subgroupLabelE = function() private$..subgroupLabelE$value,
        subgroupLabelC = function() private$..subgroupLabelC$value,
        subgroupLabelLeft = function() private$..subgroupLabelLeft$value,
        subgroupLabelRight = function() private$..subgroupLabelRight$value,
        subgroupForestWidthAdjust = function() private$..subgroupForestWidthAdjust$value,
        subgroupForestWidthUnit = function() private$..subgroupForestWidthUnit$value,
        subgroupForestHeightAdjust = function() private$..subgroupForestHeightAdjust$value,
        subgroupForestHeightUnit = function() private$..subgroupForestHeightUnit$value,
        subgroupXlimMode = function() private$..subgroupXlimMode$value,
        subgroupXlimLower = function() private$..subgroupXlimLower$value,
        subgroupXlimUpper = function() private$..subgroupXlimUpper$value,
        subgroupAddrowsMode = function() private$..subgroupAddrowsMode$value,
        subgroupAddrowsBelowOverall = function() private$..subgroupAddrowsBelowOverall$value,
        subgroupColgap = function() private$..subgroupColgap$value,
        subgroupColgapUnit = function() private$..subgroupColgapUnit$value,
        subgroupColgapForest = function() private$..subgroupColgapForest$value,
        subgroupColgapForestUnit = function() private$..subgroupColgapForestUnit$value),
    private = list(
        ..studyLabel = NA,
        ..meanE = NA,
        ..sdE = NA,
        ..nE = NA,
        ..meanC = NA,
        ..sdC = NA,
        ..nC = NA,
        ..sm = NA,
        ..methodSmd = NA,
        ..model = NA,
        ..methodTau = NA,
        ..methodRandomCi = NA,
        ..prediction = NA,
        ..confidenceLevel = NA,
        ..showSummary = NA,
        ..forestPlot = NA,
        ..forestMode = NA,
        ..forestLayout = NA,
        ..sortBy = NA,
        ..labelE = NA,
        ..labelC = NA,
        ..labelLeft = NA,
        ..labelRight = NA,
        ..forestWidthAdjust = NA,
        ..forestWidthUnit = NA,
        ..forestHeightAdjust = NA,
        ..forestHeightUnit = NA,
        ..xlimMode = NA,
        ..xlimLower = NA,
        ..xlimUpper = NA,
        ..addrowsMode = NA,
        ..addrowsBelowOverall = NA,
        ..colgap = NA,
        ..colgapUnit = NA,
        ..colgapForest = NA,
        ..colgapForestUnit = NA,
        ..subgroupVariable = NA,
        ..tauCommon = NA,
        ..predictionSubgroup = NA,
        ..showSubgroupSummary = NA,
        ..subgroupForestPlot = NA,
        ..subgroupForestMode = NA,
        ..printSubgroupName = NA,
        ..subgroupForestLayout = NA,
        ..subgroupSortBy = NA,
        ..subgroupLabelE = NA,
        ..subgroupLabelC = NA,
        ..subgroupLabelLeft = NA,
        ..subgroupLabelRight = NA,
        ..subgroupForestWidthAdjust = NA,
        ..subgroupForestWidthUnit = NA,
        ..subgroupForestHeightAdjust = NA,
        ..subgroupForestHeightUnit = NA,
        ..subgroupXlimMode = NA,
        ..subgroupXlimLower = NA,
        ..subgroupXlimUpper = NA,
        ..subgroupAddrowsMode = NA,
        ..subgroupAddrowsBelowOverall = NA,
        ..subgroupColgap = NA,
        ..subgroupColgapUnit = NA,
        ..subgroupColgapForest = NA,
        ..subgroupColgapForestUnit = NA)
)

metaContResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "metaContResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        plot = function() private$.items[["plot"]],
        subgroupText = function() private$.items[["subgroupText"]],
        subgroupPlot = function() private$.items[["subgroupPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Continuous Meta-Analysis")
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                visible="(showSummary)",
                refs=list(
                    "metaPackage")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Forest Plot",
                renderFun=".forestPlot",
                visible="(forestPlot)",
                clearWith=list(
                    "meanE",
                    "sdE",
                    "nE",
                    "meanC",
                    "sdC",
                    "nC",
                    "studyLabel",
                    "sm",
                    "methodTau",
                    "methodSmd",
                    "methodRandomCi",
                    "model",
                    "prediction",
                    "confidenceLevel",
                    "forestLayout",
                    "sortBy",
                    "labelE",
                    "labelC",
                    "labelLeft",
                    "labelRight",
                    "forestWidthAdjust",
                    "forestWidthUnit",
                    "forestHeightAdjust",
                    "forestHeightUnit",
                    "xlimMode",
                    "xlimLower",
                    "xlimUpper",
                    "addrowsMode",
                    "addrowsBelowOverall",
                    "colgap",
                    "colgapUnit",
                    "colgapForest",
                    "colgapForestUnit"),
                refs=list(
                    "metaPackage")))
            self$add(jmvcore::Html$new(
                options=options,
                name="subgroupText",
                visible=FALSE,
                refs=list(
                    "metaPackage")))
            self$add(jmvcore::Image$new(
                options=options,
                name="subgroupPlot",
                title="Subgroup Forest Plot",
                renderFun=".subgroupForestPlot",
                visible=FALSE,
                clearWith=list(
                    "meanE",
                    "sdE",
                    "nE",
                    "meanC",
                    "sdC",
                    "nC",
                    "studyLabel",
                    "sm",
                    "methodTau",
                    "methodSmd",
                    "methodRandomCi",
                    "model",
                    "prediction",
                    "confidenceLevel",
                    "subgroupVariable",
                    "tauCommon",
                    "predictionSubgroup",
                    "printSubgroupName",
                    "subgroupForestLayout",
                    "subgroupSortBy",
                    "subgroupLabelE",
                    "subgroupLabelC",
                    "subgroupLabelLeft",
                    "subgroupLabelRight",
                    "subgroupForestWidthAdjust",
                    "subgroupForestWidthUnit",
                    "subgroupForestHeightAdjust",
                    "subgroupForestHeightUnit",
                    "subgroupXlimMode",
                    "subgroupXlimLower",
                    "subgroupXlimUpper",
                    "subgroupAddrowsMode",
                    "subgroupAddrowsBelowOverall",
                    "subgroupColgap",
                    "subgroupColgapUnit",
                    "subgroupColgapForest",
                    "subgroupColgapForestUnit"),
                refs=list(
                    "metaPackage")))}))

metaContBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "metaContBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "MetaPort",
                name = "metaCont",
                version = c(1,0,0),
                options = options,
                results = metaContResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Continuous Meta-Analysis
#'
#' 
#' @param data .
#' @param studyLabel .
#' @param meanE .
#' @param sdE .
#' @param nE .
#' @param meanC .
#' @param sdC .
#' @param nC .
#' @param sm .
#' @param methodSmd .
#' @param model .
#' @param methodTau .
#' @param methodRandomCi .
#' @param prediction .
#' @param confidenceLevel .
#' @param showSummary .
#' @param forestPlot .
#' @param forestMode .
#' @param forestLayout .
#' @param sortBy .
#' @param labelE .
#' @param labelC .
#' @param labelLeft .
#' @param labelRight .
#' @param forestWidthAdjust .
#' @param forestWidthUnit .
#' @param forestHeightAdjust .
#' @param forestHeightUnit .
#' @param xlimMode .
#' @param xlimLower .
#' @param xlimUpper .
#' @param addrowsMode .
#' @param addrowsBelowOverall .
#' @param colgap .
#' @param colgapUnit .
#' @param colgapForest .
#' @param colgapForestUnit .
#' @param subgroupVariable .
#' @param tauCommon .
#' @param predictionSubgroup .
#' @param showSubgroupSummary .
#' @param subgroupForestPlot .
#' @param subgroupForestMode .
#' @param printSubgroupName .
#' @param subgroupForestLayout .
#' @param subgroupSortBy .
#' @param subgroupLabelE .
#' @param subgroupLabelC .
#' @param subgroupLabelLeft .
#' @param subgroupLabelRight .
#' @param subgroupForestWidthAdjust .
#' @param subgroupForestWidthUnit .
#' @param subgroupForestHeightAdjust .
#' @param subgroupForestHeightUnit .
#' @param subgroupXlimMode .
#' @param subgroupXlimLower .
#' @param subgroupXlimUpper .
#' @param subgroupAddrowsMode .
#' @param subgroupAddrowsBelowOverall .
#' @param subgroupColgap .
#' @param subgroupColgapUnit .
#' @param subgroupColgapForest .
#' @param subgroupColgapForestUnit .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$subgroupText} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$subgroupPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
metaCont <- function(
    data,
    studyLabel,
    meanE,
    sdE,
    nE,
    meanC,
    sdC,
    nC,
    sm = "md",
    methodSmd = "Hedges",
    model = "both",
    methodTau = "REML",
    methodRandomCi = "classic",
    prediction = FALSE,
    confidenceLevel = 95,
    showSummary = TRUE,
    forestPlot = TRUE,
    forestMode = "basic",
    forestLayout = "meta",
    sortBy = "none",
    labelE = "Experimental",
    labelC = "Control",
    labelLeft = "",
    labelRight = "",
    forestWidthAdjust = 0,
    forestWidthUnit = "mm",
    forestHeightAdjust = 0,
    forestHeightUnit = "mm",
    xlimMode = "auto",
    xlimLower = -20,
    xlimUpper = 20,
    addrowsMode = "auto",
    addrowsBelowOverall = 0,
    colgap = 2,
    colgapUnit = "mm",
    colgapForest = 2,
    colgapForestUnit = "mm",
    subgroupVariable,
    tauCommon = FALSE,
    predictionSubgroup = FALSE,
    showSubgroupSummary = TRUE,
    subgroupForestPlot = TRUE,
    subgroupForestMode = "basic",
    printSubgroupName = TRUE,
    subgroupForestLayout = "meta",
    subgroupSortBy = "none",
    subgroupLabelE = "Experimental",
    subgroupLabelC = "Control",
    subgroupLabelLeft = "",
    subgroupLabelRight = "",
    subgroupForestWidthAdjust = 0,
    subgroupForestWidthUnit = "mm",
    subgroupForestHeightAdjust = 0,
    subgroupForestHeightUnit = "mm",
    subgroupXlimMode = "auto",
    subgroupXlimLower = -20,
    subgroupXlimUpper = 20,
    subgroupAddrowsMode = "auto",
    subgroupAddrowsBelowOverall = 0,
    subgroupColgap = 2,
    subgroupColgapUnit = "mm",
    subgroupColgapForest = 2,
    subgroupColgapForestUnit = "mm") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("metaCont requires jmvcore to be installed (restart may be required)")

    if ( ! missing(studyLabel)) studyLabel <- jmvcore::resolveQuo(jmvcore::enquo(studyLabel))
    if ( ! missing(meanE)) meanE <- jmvcore::resolveQuo(jmvcore::enquo(meanE))
    if ( ! missing(sdE)) sdE <- jmvcore::resolveQuo(jmvcore::enquo(sdE))
    if ( ! missing(nE)) nE <- jmvcore::resolveQuo(jmvcore::enquo(nE))
    if ( ! missing(meanC)) meanC <- jmvcore::resolveQuo(jmvcore::enquo(meanC))
    if ( ! missing(sdC)) sdC <- jmvcore::resolveQuo(jmvcore::enquo(sdC))
    if ( ! missing(nC)) nC <- jmvcore::resolveQuo(jmvcore::enquo(nC))
    if ( ! missing(subgroupVariable)) subgroupVariable <- jmvcore::resolveQuo(jmvcore::enquo(subgroupVariable))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(studyLabel), studyLabel, NULL),
            `if`( ! missing(meanE), meanE, NULL),
            `if`( ! missing(sdE), sdE, NULL),
            `if`( ! missing(nE), nE, NULL),
            `if`( ! missing(meanC), meanC, NULL),
            `if`( ! missing(sdC), sdC, NULL),
            `if`( ! missing(nC), nC, NULL),
            `if`( ! missing(subgroupVariable), subgroupVariable, NULL))


    options <- metaContOptions$new(
        studyLabel = studyLabel,
        meanE = meanE,
        sdE = sdE,
        nE = nE,
        meanC = meanC,
        sdC = sdC,
        nC = nC,
        sm = sm,
        methodSmd = methodSmd,
        model = model,
        methodTau = methodTau,
        methodRandomCi = methodRandomCi,
        prediction = prediction,
        confidenceLevel = confidenceLevel,
        showSummary = showSummary,
        forestPlot = forestPlot,
        forestMode = forestMode,
        forestLayout = forestLayout,
        sortBy = sortBy,
        labelE = labelE,
        labelC = labelC,
        labelLeft = labelLeft,
        labelRight = labelRight,
        forestWidthAdjust = forestWidthAdjust,
        forestWidthUnit = forestWidthUnit,
        forestHeightAdjust = forestHeightAdjust,
        forestHeightUnit = forestHeightUnit,
        xlimMode = xlimMode,
        xlimLower = xlimLower,
        xlimUpper = xlimUpper,
        addrowsMode = addrowsMode,
        addrowsBelowOverall = addrowsBelowOverall,
        colgap = colgap,
        colgapUnit = colgapUnit,
        colgapForest = colgapForest,
        colgapForestUnit = colgapForestUnit,
        subgroupVariable = subgroupVariable,
        tauCommon = tauCommon,
        predictionSubgroup = predictionSubgroup,
        showSubgroupSummary = showSubgroupSummary,
        subgroupForestPlot = subgroupForestPlot,
        subgroupForestMode = subgroupForestMode,
        printSubgroupName = printSubgroupName,
        subgroupForestLayout = subgroupForestLayout,
        subgroupSortBy = subgroupSortBy,
        subgroupLabelE = subgroupLabelE,
        subgroupLabelC = subgroupLabelC,
        subgroupLabelLeft = subgroupLabelLeft,
        subgroupLabelRight = subgroupLabelRight,
        subgroupForestWidthAdjust = subgroupForestWidthAdjust,
        subgroupForestWidthUnit = subgroupForestWidthUnit,
        subgroupForestHeightAdjust = subgroupForestHeightAdjust,
        subgroupForestHeightUnit = subgroupForestHeightUnit,
        subgroupXlimMode = subgroupXlimMode,
        subgroupXlimLower = subgroupXlimLower,
        subgroupXlimUpper = subgroupXlimUpper,
        subgroupAddrowsMode = subgroupAddrowsMode,
        subgroupAddrowsBelowOverall = subgroupAddrowsBelowOverall,
        subgroupColgap = subgroupColgap,
        subgroupColgapUnit = subgroupColgapUnit,
        subgroupColgapForest = subgroupColgapForest,
        subgroupColgapForestUnit = subgroupColgapForestUnit)

    analysis <- metaContClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

