
# This file is automatically generated, you probably don't want to edit this

mpcontOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mpcontOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mean.e = NULL,
            sd.e = NULL,
            n.e = NULL,
            mean.c = NULL,
            sd.c = NULL,
            n.c = NULL,
            id = NULL,
            sm = "MD",
            random = TRUE,
            common = TRUE,
            label.e = NULL,
            label.c = NULL, ...) {

            super$initialize(
                package="MetaPort",
                name="mpcont",
                requiresData=TRUE,
                ...)

            private$..mean.e <- jmvcore::OptionVariable$new(
                "mean.e",
                mean.e)
            private$..sd.e <- jmvcore::OptionVariable$new(
                "sd.e",
                sd.e)
            private$..n.e <- jmvcore::OptionVariable$new(
                "n.e",
                n.e)
            private$..mean.c <- jmvcore::OptionVariable$new(
                "mean.c",
                mean.c)
            private$..sd.c <- jmvcore::OptionVariable$new(
                "sd.c",
                sd.c)
            private$..n.c <- jmvcore::OptionVariable$new(
                "n.c",
                n.c)
            private$..id <- jmvcore::OptionVariable$new(
                "id",
                id)
            private$..sm <- jmvcore::OptionList$new(
                "sm",
                sm,
                options=list(
                    "MD",
                    "SMD"),
                default="MD")
            private$..random <- jmvcore::OptionBool$new(
                "random",
                random,
                default=TRUE)
            private$..common <- jmvcore::OptionBool$new(
                "common",
                common,
                default=TRUE)
            private$..label.e <- jmvcore::OptionString$new(
                "label.e",
                label.e)
            private$..label.c <- jmvcore::OptionString$new(
                "label.c",
                label.c)

            self$.addOption(private$..mean.e)
            self$.addOption(private$..sd.e)
            self$.addOption(private$..n.e)
            self$.addOption(private$..mean.c)
            self$.addOption(private$..sd.c)
            self$.addOption(private$..n.c)
            self$.addOption(private$..id)
            self$.addOption(private$..sm)
            self$.addOption(private$..random)
            self$.addOption(private$..common)
            self$.addOption(private$..label.e)
            self$.addOption(private$..label.c)
        }),
    active = list(
        mean.e = function() private$..mean.e$value,
        sd.e = function() private$..sd.e$value,
        n.e = function() private$..n.e$value,
        mean.c = function() private$..mean.c$value,
        sd.c = function() private$..sd.c$value,
        n.c = function() private$..n.c$value,
        id = function() private$..id$value,
        sm = function() private$..sm$value,
        random = function() private$..random$value,
        common = function() private$..common$value,
        label.e = function() private$..label.e$value,
        label.c = function() private$..label.c$value),
    private = list(
        ..mean.e = NA,
        ..sd.e = NA,
        ..n.e = NA,
        ..mean.c = NA,
        ..sd.c = NA,
        ..n.c = NA,
        ..id = NA,
        ..sm = NA,
        ..random = NA,
        ..common = NA,
        ..label.e = NA,
        ..label.c = NA)
)

mpcontResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mpcontResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        plot = function() private$.items[["plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Meta-analysis of continuous outcome data")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Results for Overall meta analysis"))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Forest Plot",
                width=800,
                height=1000,
                renderFun=".plot"))}))

mpcontBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mpcontBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "MetaPort",
                name = "mpcont",
                version = c(1,0,0),
                options = options,
                results = mpcontResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Meta-analysis of continuous outcome data
#'
#' 
#' @param data .
#' @param mean.e .
#' @param sd.e .
#' @param n.e .
#' @param mean.c .
#' @param sd.c .
#' @param n.c .
#' @param id .
#' @param sm .
#' @param random .
#' @param common .
#' @param label.e .
#' @param label.c .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
mpcont <- function(
    data,
    mean.e,
    sd.e,
    n.e,
    mean.c,
    sd.c,
    n.c,
    id,
    sm = "MD",
    random = TRUE,
    common = TRUE,
    label.e,
    label.c) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mpcont requires jmvcore to be installed (restart may be required)")

    if ( ! missing(mean.e)) mean.e <- jmvcore::resolveQuo(jmvcore::enquo(mean.e))
    if ( ! missing(sd.e)) sd.e <- jmvcore::resolveQuo(jmvcore::enquo(sd.e))
    if ( ! missing(n.e)) n.e <- jmvcore::resolveQuo(jmvcore::enquo(n.e))
    if ( ! missing(mean.c)) mean.c <- jmvcore::resolveQuo(jmvcore::enquo(mean.c))
    if ( ! missing(sd.c)) sd.c <- jmvcore::resolveQuo(jmvcore::enquo(sd.c))
    if ( ! missing(n.c)) n.c <- jmvcore::resolveQuo(jmvcore::enquo(n.c))
    if ( ! missing(id)) id <- jmvcore::resolveQuo(jmvcore::enquo(id))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(mean.e), mean.e, NULL),
            `if`( ! missing(sd.e), sd.e, NULL),
            `if`( ! missing(n.e), n.e, NULL),
            `if`( ! missing(mean.c), mean.c, NULL),
            `if`( ! missing(sd.c), sd.c, NULL),
            `if`( ! missing(n.c), n.c, NULL),
            `if`( ! missing(id), id, NULL))


    options <- mpcontOptions$new(
        mean.e = mean.e,
        sd.e = sd.e,
        n.e = n.e,
        mean.c = mean.c,
        sd.c = sd.c,
        n.c = n.c,
        id = id,
        sm = sm,
        random = random,
        common = common,
        label.e = label.e,
        label.c = label.c)

    analysis <- mpcontClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

