
# This file is automatically generated, you probably don't want to edit this

mpcontOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mpcontOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            studyLabel = NULL,
            meanE = NULL,
            sdE = NULL,
            nE = NULL,
            meanC = NULL,
            sdC = NULL,
            nC = NULL,
            MetaRegressionCovariate = NULL,
            sm = "md",
            methodSmd = "hedges",
            random = TRUE,
            common = TRUE,
            methodTau = "reml",
            prediction = FALSE,
            confidenceLevel = 0.95,
            groupLabelE = "Experimental",
            groupLabelC = "Control",
            forestPlot = TRUE,
            LOO = FALSE,
            metaRegressionEnabled = FALSE, ...) {

            super$initialize(
                package="MetaPort",
                name="mpcont",
                requiresData=TRUE,
                ...)

            private$..studyLabel <- jmvcore::OptionVariable$new(
                "studyLabel",
                studyLabel,
                suggested=list(
                    "nominal",
                    "ordinal",
                    "id"))
            private$..meanE <- jmvcore::OptionVariable$new(
                "meanE",
                meanE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sdE <- jmvcore::OptionVariable$new(
                "sdE",
                sdE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..nE <- jmvcore::OptionVariable$new(
                "nE",
                nE,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..meanC <- jmvcore::OptionVariable$new(
                "meanC",
                meanC,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sdC <- jmvcore::OptionVariable$new(
                "sdC",
                sdC,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..nC <- jmvcore::OptionVariable$new(
                "nC",
                nC,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..MetaRegressionCovariate <- jmvcore::OptionVariable$new(
                "MetaRegressionCovariate",
                MetaRegressionCovariate,
                suggested=list(
                    "continuous"),
                permitted=list(
                    "numeric"))
            private$..sm <- jmvcore::OptionList$new(
                "sm",
                sm,
                options=list(
                    "md",
                    "smd",
                    "rom"),
                default="md")
            private$..methodSmd <- jmvcore::OptionList$new(
                "methodSmd",
                methodSmd,
                options=list(
                    "hedges",
                    "cohen",
                    "glass"),
                default="hedges")
            private$..random <- jmvcore::OptionBool$new(
                "random",
                random,
                default=TRUE)
            private$..common <- jmvcore::OptionBool$new(
                "common",
                common,
                default=TRUE)
            private$..methodTau <- jmvcore::OptionList$new(
                "methodTau",
                methodTau,
                options=list(
                    "reml",
                    "dl",
                    "pm",
                    "ml",
                    "hs",
                    "sj",
                    "he",
                    "eb"),
                default="reml")
            private$..prediction <- jmvcore::OptionBool$new(
                "prediction",
                prediction,
                default=FALSE)
            private$..confidenceLevel <- jmvcore::OptionNumber$new(
                "confidenceLevel",
                confidenceLevel,
                default=0.95)
            private$..groupLabelE <- jmvcore::OptionString$new(
                "groupLabelE",
                groupLabelE,
                default="Experimental")
            private$..groupLabelC <- jmvcore::OptionString$new(
                "groupLabelC",
                groupLabelC,
                default="Control")
            private$..forestPlot <- jmvcore::OptionBool$new(
                "forestPlot",
                forestPlot,
                default=TRUE)
            private$..LOO <- jmvcore::OptionBool$new(
                "LOO",
                LOO,
                default=FALSE)
            private$..metaRegressionEnabled <- jmvcore::OptionBool$new(
                "metaRegressionEnabled",
                metaRegressionEnabled,
                default=FALSE)

            self$.addOption(private$..studyLabel)
            self$.addOption(private$..meanE)
            self$.addOption(private$..sdE)
            self$.addOption(private$..nE)
            self$.addOption(private$..meanC)
            self$.addOption(private$..sdC)
            self$.addOption(private$..nC)
            self$.addOption(private$..MetaRegressionCovariate)
            self$.addOption(private$..sm)
            self$.addOption(private$..methodSmd)
            self$.addOption(private$..random)
            self$.addOption(private$..common)
            self$.addOption(private$..methodTau)
            self$.addOption(private$..prediction)
            self$.addOption(private$..confidenceLevel)
            self$.addOption(private$..groupLabelE)
            self$.addOption(private$..groupLabelC)
            self$.addOption(private$..forestPlot)
            self$.addOption(private$..LOO)
            self$.addOption(private$..metaRegressionEnabled)
        }),
    active = list(
        studyLabel = function() private$..studyLabel$value,
        meanE = function() private$..meanE$value,
        sdE = function() private$..sdE$value,
        nE = function() private$..nE$value,
        meanC = function() private$..meanC$value,
        sdC = function() private$..sdC$value,
        nC = function() private$..nC$value,
        MetaRegressionCovariate = function() private$..MetaRegressionCovariate$value,
        sm = function() private$..sm$value,
        methodSmd = function() private$..methodSmd$value,
        random = function() private$..random$value,
        common = function() private$..common$value,
        methodTau = function() private$..methodTau$value,
        prediction = function() private$..prediction$value,
        confidenceLevel = function() private$..confidenceLevel$value,
        groupLabelE = function() private$..groupLabelE$value,
        groupLabelC = function() private$..groupLabelC$value,
        forestPlot = function() private$..forestPlot$value,
        LOO = function() private$..LOO$value,
        metaRegressionEnabled = function() private$..metaRegressionEnabled$value),
    private = list(
        ..studyLabel = NA,
        ..meanE = NA,
        ..sdE = NA,
        ..nE = NA,
        ..meanC = NA,
        ..sdC = NA,
        ..nC = NA,
        ..MetaRegressionCovariate = NA,
        ..sm = NA,
        ..methodSmd = NA,
        ..random = NA,
        ..common = NA,
        ..methodTau = NA,
        ..prediction = NA,
        ..confidenceLevel = NA,
        ..groupLabelE = NA,
        ..groupLabelC = NA,
        ..forestPlot = NA,
        ..LOO = NA,
        ..metaRegressionEnabled = NA)
)

mpcontResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mpcontResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        plot = function() private$.items[["plot"]],
        LOOText = function() private$.items[["LOOText"]],
        LOOPlot = function() private$.items[["LOOPlot"]],
        meta_regression_text = function() private$.items[["meta_regression_text"]],
        meta_regression_plot = function() private$.items[["meta_regression_plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Meta-analysis of continuous outcome data")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Results for Overall meta analysis",
                clearWith=list(
                    "meanE",
                    "sdE",
                    "nE",
                    "meanC",
                    "sdC",
                    "nC",
                    "studyLabel",
                    "groupLabelE",
                    "groupLabelC",
                    "sm",
                    "methodTau",
                    "methodSmd",
                    "random",
                    "common",
                    "prediction",
                    "confidenceLevel"),
                refs=list(
                    "metaPackage")))
            self$add(jmvcore::Image$new(
                options=options,
                name="plot",
                title="Forest Plot",
                width=800,
                height=1000,
                renderFun=".forestPlot",
                visible="(forestPlot)",
                requiresData=TRUE,
                clearWith=list(
                    "meanE",
                    "sdE",
                    "nE",
                    "meanC",
                    "sdC",
                    "nC",
                    "studyLabel",
                    "groupLabelE",
                    "groupLabelC",
                    "sm",
                    "methodTau",
                    "methodSmd",
                    "random",
                    "common",
                    "prediction",
                    "confidenceLevel"),
                refs=list(
                    "metaPackage")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="LOOText",
                title="leave-one-out Analysis",
                visible="(LOO)",
                clearWith=list(
                    "meanE",
                    "sdE",
                    "nE",
                    "meanC",
                    "sdC",
                    "nC",
                    "studyLabel",
                    "groupLabelE",
                    "groupLabelC",
                    "sm",
                    "methodTau",
                    "methodSmd",
                    "random",
                    "common",
                    "confidenceLevel"),
                refs=list(
                    "metaPackage")))
            self$add(jmvcore::Image$new(
                options=options,
                name="LOOPlot",
                title="leave-one-out Plot",
                width=800,
                height=1000,
                renderFun=".LOOPlot",
                visible="(LOO)",
                clearWith=list(
                    "meanE",
                    "sdE",
                    "nE",
                    "meanC",
                    "sdC",
                    "nC",
                    "studyLabel",
                    "groupLabelE",
                    "groupLabelC",
                    "sm",
                    "methodTau",
                    "methodSmd",
                    "random",
                    "common",
                    "confidenceLevel"),
                refs=list(
                    "metaPackage")))
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="meta_regression_text",
                title="Meta-Regression Results",
                visible="(metaRegressionEnabled)",
                clearWith=list(
                    "meanE",
                    "sdE",
                    "meanC",
                    "sdC",
                    "studyLabel",
                    "sm",
                    "methodTau",
                    "methodSmd",
                    "random",
                    "common",
                    "confidenceLevel",
                    "MetaRegressionCovariate"),
                refs=list(
                    "metaPackage")))
            self$add(jmvcore::Image$new(
                options=options,
                name="meta_regression_plot",
                title="Meta-Regression Plot",
                width=700,
                height=500,
                renderFun=".meta_reg_plot_func",
                visible="(metaRegressionEnabled)",
                clearWith=list(
                    "meanE",
                    "sdE",
                    "meanC",
                    "sdC",
                    "studyLabel",
                    "sm",
                    "methodTau",
                    "methodSmd",
                    "random",
                    "common",
                    "confidenceLevel",
                    "MetaRegressionCovariate"),
                refs=list(
                    "metaPackage")))}))

mpcontBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mpcontBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "MetaPort",
                name = "mpcont",
                version = c(1,0,0),
                options = options,
                results = mpcontResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Meta-analysis of continuous outcome data
#'
#' 
#' @param data .
#' @param studyLabel .
#' @param meanE .
#' @param sdE .
#' @param nE .
#' @param meanC .
#' @param sdC .
#' @param nC .
#' @param MetaRegressionCovariate .
#' @param sm .
#' @param methodSmd .
#' @param random .
#' @param common .
#' @param methodTau .
#' @param prediction .
#' @param confidenceLevel .
#' @param groupLabelE .
#' @param groupLabelC .
#' @param forestPlot .
#' @param LOO .
#' @param metaRegressionEnabled .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$LOOText} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$LOOPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$meta_regression_text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$meta_regression_plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' @export
mpcont <- function(
    data,
    studyLabel,
    meanE,
    sdE,
    nE,
    meanC,
    sdC,
    nC,
    MetaRegressionCovariate,
    sm = "md",
    methodSmd = "hedges",
    random = TRUE,
    common = TRUE,
    methodTau = "reml",
    prediction = FALSE,
    confidenceLevel = 0.95,
    groupLabelE = "Experimental",
    groupLabelC = "Control",
    forestPlot = TRUE,
    LOO = FALSE,
    metaRegressionEnabled = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mpcont requires jmvcore to be installed (restart may be required)")

    if ( ! missing(studyLabel)) studyLabel <- jmvcore::resolveQuo(jmvcore::enquo(studyLabel))
    if ( ! missing(meanE)) meanE <- jmvcore::resolveQuo(jmvcore::enquo(meanE))
    if ( ! missing(sdE)) sdE <- jmvcore::resolveQuo(jmvcore::enquo(sdE))
    if ( ! missing(nE)) nE <- jmvcore::resolveQuo(jmvcore::enquo(nE))
    if ( ! missing(meanC)) meanC <- jmvcore::resolveQuo(jmvcore::enquo(meanC))
    if ( ! missing(sdC)) sdC <- jmvcore::resolveQuo(jmvcore::enquo(sdC))
    if ( ! missing(nC)) nC <- jmvcore::resolveQuo(jmvcore::enquo(nC))
    if ( ! missing(MetaRegressionCovariate)) MetaRegressionCovariate <- jmvcore::resolveQuo(jmvcore::enquo(MetaRegressionCovariate))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(studyLabel), studyLabel, NULL),
            `if`( ! missing(meanE), meanE, NULL),
            `if`( ! missing(sdE), sdE, NULL),
            `if`( ! missing(nE), nE, NULL),
            `if`( ! missing(meanC), meanC, NULL),
            `if`( ! missing(sdC), sdC, NULL),
            `if`( ! missing(nC), nC, NULL),
            `if`( ! missing(MetaRegressionCovariate), MetaRegressionCovariate, NULL))


    options <- mpcontOptions$new(
        studyLabel = studyLabel,
        meanE = meanE,
        sdE = sdE,
        nE = nE,
        meanC = meanC,
        sdC = sdC,
        nC = nC,
        MetaRegressionCovariate = MetaRegressionCovariate,
        sm = sm,
        methodSmd = methodSmd,
        random = random,
        common = common,
        methodTau = methodTau,
        prediction = prediction,
        confidenceLevel = confidenceLevel,
        groupLabelE = groupLabelE,
        groupLabelC = groupLabelC,
        forestPlot = forestPlot,
        LOO = LOO,
        metaRegressionEnabled = metaRegressionEnabled)

    analysis <- mpcontClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

